from .stop import StopOpcode
from .add import AddOpcode
from .mul import MulOpcode
from .sub import SubOpcode
from .div import DivOpcode
from .sdiv import SdivOpcode
from .mod import ModOpcode
from .smod import SmodOpcode
from .addmod import AddmodOpcode
from .mulmod import MulmodOpcode
from .exp import ExpOpcode
from .signextend import SignextendOpcode
from .lt import LtOpcode
from .gt import GtOpcode
from .slt import SltOpcode
from .sgt import SgtOpcode
from .eq import EqOpcode
from .iszero import IszeroOpcode
from .and_code import AndOpcode
from .or_code import OrOpcode
from .xor import XorOpcode
from .not_code import NotOpcode
from .byte import ByteOpcode
from .shl import ShlOpcode
from .shr import ShrOpcode
from .sar import SarOpcode
from .rol import RolOpcode
from .ror import RorOpcode
from .keccak256 import Keccak256Opcode
from .address import AddressOpcode
from .balance import BalanceOpcode
from .origin import OriginOpcode
from .caller import CallerOpcode
from .callvalue import CallvalueOpcode
from .calldataload import CalldataloadOpcode
from .calldatasize import CalldatasizeOpcode
from .calldatacopy import CalldatacopyOpcode
from .codesize import CodesizeOpcode
from .codecopy import CodecopyOpcode
from .gasprice import GaspriceOpcode
from .extcodesize import ExtcodesizeOpcode
from .extcodecopy import ExtcodecopyOpcode
from .blockhash import BlockhashOpcode
from .coinbase import CoinbaseOpcode
from .timestamp import TimestampOpcode
from .number import NumberOpcode
from .difficulty import DifficultyOpcode
from .gaslimit import GaslimitOpcode
from .pop import PopOpcode
from .mload import MloadOpcode
from .mstore import MstoreOpcode
from .mstore8 import Mstore8Opcode
from .sload import SloadOpcode
from .sstore import SstoreOpcode
from .swap import SwapOpcode
from .jump import JumpOpcode
from .jumpi import JumpiOpcode
from .pc import PcOpcode
from .msize import MsizeOpcode
from .gas import GasOpcode
from .jumpdest import JumpdestOpcode
from .create import CreateOpcode
from .call import CallOpcode
from .callcode import CallcodeOpcode
from .return_code import ReturnOpcode
from .delegatecall import DelegatecallOpcode
from .staticcall import StaticcallOpcode
from .revert import RevertOpcode
from .selfdestruct import SelfdestructOpcode
from .push import PushOpcode
from .dup import DupOpcode
from .log import LogOpcode
